"""Unit tests for freedom_portfolio.auth — no network access."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

# Make src/ importable when running pytest from the repo root.
_SRC = Path(__file__).resolve().parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from freedom_portfolio.auth import build_request, build_signature  # noqa: E402


def test_signature_known_vector():
    """
    Reference vector: serialise sorted "key=value" pairs without separator,
    append the secret, md5.  Computed independently in this test.
    """
    params = {"apiKey": "testkey", "cmd": "getPortfolio", "nonce": "1700000000000"}
    expected_input = "apiKey=testkeycmd=getPortfoliononce=1700000000000mysecret"
    expected_sig = hashlib.md5(expected_input.encode()).hexdigest()
    assert expected_sig == "6310362099a209c5c0f5bc5a51051493"
    assert build_signature(params, "mysecret") == expected_sig


def test_signature_handles_nested_params():
    """Nested dicts are serialised recursively in place of their value."""
    params = {
        "apiKey": "testkey",
        "cmd":    "getPortfolio",
        "nonce":  "1700000000000",
        "params": {"is_re_eval": True},
    }
    # bool True → "1" per Tradernet PHP serialisation; nested concat = "is_re_eval=1"
    expected_input = (
        "apiKey=testkeycmd=getPortfoliononce=1700000000000params=is_re_eval=1mysecret"
    )
    expected_sig = hashlib.md5(expected_input.encode()).hexdigest()
    assert build_signature(params, "mysecret") == expected_sig


def test_signature_sorts_alphabetically():
    """Insertion order must not affect the signature — only sorted order."""
    a = {"b": "2", "a": "1", "c": "3"}
    b = {"c": "3", "a": "1", "b": "2"}
    assert build_signature(a, "s") == build_signature(b, "s")


def test_build_request_adds_required_fields():
    body = build_request("getPortfolio", {}, "pubk", "sec", nonce="1700000000000")
    assert body["apiKey"] == "pubk"
    assert body["cmd"]    == "getPortfolio"
    assert body["nonce"]  == "1700000000000"
    assert body["params"] == {}
    assert "sig" in body
    assert len(body["sig"]) == 32  # md5 hex


def test_nonce_is_string_when_autogenerated():
    body = build_request("getPortfolio", {}, "pubk", "sec")
    assert isinstance(body["nonce"], str)
    assert body["nonce"].isdigit()


def test_signature_does_not_include_sig_field():
    """build_request must not feed an existing 'sig' back into signing."""
    body = build_request("getPortfolio", {}, "pubk", "sec", nonce="1")
    # Re-derive the signature without the "sig" key — must match.
    derived = build_signature({k: v for k, v in body.items() if k != "sig"}, "sec")
    assert body["sig"] == derived
