"""
HTML Report Renderer — Jinja2-only (no Chromium, no PDF).

Replaces the previous pdf_generator.py.  The bot now ships HTML reports
via a signed Cloud Storage URL (see services.report_storage) instead of
rendering a PDF — this drops Playwright + Chromium from the runtime
(~1.1 GB image shrinkage) and lets the reports remain interactive,
zoomable and mobile-friendly in the user's own browser.

Two layouts:
  • report_basic.html — BASE-tier report (tier='base')
  • report_deep.html  — DEEP-tier report (tier='deep')

Legacy `report.html` (dark theme) is kept as a fallback when
REPORT_VERSION=v1 in the environment.

The renderer writes the rendered HTML to /tmp by default; callers
typically pass the path to services.report_storage.upload_report() to
push the file to GCS and obtain a signed URL.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent / "templates"
# Reports are temporary by design — /tmp survives only until container
# restart, but each report should already be in GCS by then.
OUTPUT_DIR   = Path(os.getenv("REPORT_LOCAL_DIR", "/tmp/user_reports"))

# Feature flag: 'v2' (default) → light theme basic/deep; 'v1' → legacy report.html
REPORT_VERSION = os.getenv("REPORT_VERSION", "v2").lower()


# Minimal mock fixture for the CLI smoke test below.  Built through
# build_payload so it carries every key the templates expect.  Full
# real-data fixtures live in tests/test_phase4_reporting.py.
def _mock_results() -> dict:
    """Synthetic results dict that build_payload can chew on."""
    import pandas as pd
    perf = pd.DataFrame([
        {"Ticker": "AAPL", "Current_Value": 25000.0, "Total_Cost": 20000.0,
         "PnL": 5000.0, "Return_Pct": 0.25,
         "Euler_Risk_Contribution_Pct": 18.4, "ATR_Pct": 1.4,
         "Fundamental_Sector": "Technology"},
        {"Ticker": "KSPI", "Current_Value": 15000.0, "Total_Cost": 18000.0,
         "PnL": -3000.0, "Return_Pct": -0.167,
         "Euler_Risk_Contribution_Pct": 22.1, "ATR_Pct": 2.1,
         "Fundamental_Sector": "EM_Kazakhstan"},
        {"Ticker": "BND",  "Current_Value": 10000.0, "Total_Cost": 10000.0,
         "PnL": 0.0, "Return_Pct": 0.0,
         "Euler_Risk_Contribution_Pct": 3.2, "ATR_Pct": 0.4,
         "Fundamental_Sector": "Fixed_Income"},
    ])
    return {
        "performance_table": perf,
        "total_value": 50000.0,
        "portfolio_metrics": {
            "CVaR_95_Daily": -0.052, "Sharpe_Ratio": 1.34,
            "Sortino_Ratio": 1.62, "VaR_95_Daily": -0.024,
            "Max_Drawdown": -0.128, "Total_Volatility_Ann": 0.142,
            "Composite_Risk_Score": 62, "Max_Euler_Risk_Pct": 22.1,
            "CVaR_95_Bootstrap": {"point": -0.052, "lo95": -0.07, "hi95": -0.045},
        },
        "sector_exposure": {"Technology": 0.50, "EM_Kazakhstan": 0.30,
                             "Fixed_Income": 0.20},
        "benchmark_comparison": {},
        "asset_scores": {},
    }


def _mock_payload(tier: str = "base") -> dict:
    """
    Build a mock payload via build_payload so every key is present.

    For DEEP tier we additionally inject `factor_radar_svg` and
    `factor_betas` — these are normally produced inside tg_bot.py from
    Beta_<axis> columns in the perf table, so the smoke fixture needs
    to mimic that out-of-band wiring.

    DEEP also synthesises mock values for engine-heavy keys that need
    external services (FRED, stress engine, BL simulate):
      stress_scenarios, expected_effect, macro_drivers, regime,
      action_plan, hotspots, risk_waterfall.
    The shapes match what the live engine emits — same field names and
    types — so the template binds the same way in production.
    """
    from pdf_payload import build_payload
    # Tier-specific model — mirrors src/ai_narrative.py:
    #   MODEL_BASE = claude-haiku-4-5-20251001
    #   MODEL_DEEP = claude-sonnet-4-6
    # The DEEP report's AI commentary is generated by Sonnet (richer
    # reasoning required for stress / regime / scoring narrative).
    _mock_model = ("claude-sonnet-4-6" if tier == "deep"
                    else "claude-haiku-4-5-20251001")
    payload = build_payload(
        _mock_results(),
        tier=tier,
        ai_summary={
            "verdict":        "Портфель в умеренной зоне риска (composite 62/100).",
            "plain_summary":  "За месяц портфель прибавил +5.8%.  Главные риски — "
                              "перевес в технологиях и KSPI hotspot (TRC 22%).",
            "bullets":        ["AAPL +25% от входа — крупнейший вклад",
                                "KSPI просел −16.7%, TRC 22% — пересмотр позиции"],
            "stock_picks":    {},
            "used_rag":       False,
            "model_used":     _mock_model,
        },
    )
    if tier == "deep":
        # Mirror the post-build enrichment done in tg_bot._render_v2 so the
        # new factor + CoVe sections actually populate in the smoke render.
        try:
            from tg_bot import (_build_equity_curve_svg,
                                  _build_factor_radar_svg,
                                  _build_factor_betas_table)
            results = _mock_results()
            payload["equity_curve_svg"] = _build_equity_curve_svg(results)
            payload["factor_radar_svg"] = _build_factor_radar_svg(results)
            payload["factor_betas"]     = _build_factor_betas_table(results)
        except Exception as exc:
            # tg_bot has many heavy deps (aiogram); fall back to a synthetic
            # radar + an 8-row table so the template at least renders cleanly.
            logger.warning("Smoke fallback for radar — tg_bot import failed: %s", exc)
            from pdf_charts import factor_radar_svg
            mock_betas = {
                "Market":     1.18,  "Momentum": 1.05, "Value":      0.25,
                "Quality":    0.62,  "Size":     0.42, "Volatility": 0.88,
                "Commodities":0.15,  "Rates":   -0.30,
            }
            payload["factor_radar_svg"] = factor_radar_svg(mock_betas)
            payload["factor_betas"]     = [
                {"axis": a, "beta": b,
                 "bench":  1.0 if a == "Market" else 0.0,
                 "delta":  round(b - (1.0 if a == "Market" else 0.0), 2),
                 "missing": False}
                for a, b in mock_betas.items()
            ]
        # Synthesise mock stress/effect/macro/regime so the design pages
        # render fully populated.  Engine produces identical shapes in
        # production from real inputs (FRED + simulate_after_plan).
        payload["stress_scenarios"] = _MOCK_STRESS_SCENARIOS
        payload["expected_effect"]  = _MOCK_EXPECTED_EFFECT
        payload["macro_drivers"]    = _MOCK_MACRO_DRIVERS
        payload["regime"]           = _MOCK_REGIME
        payload["action_plan"]      = _MOCK_ACTION_PLAN
        payload["hotspots"]         = _MOCK_HOTSPOTS
        payload["risk_waterfall"]   = _MOCK_RISK_WATERFALL
        payload["score_breakdown"]  = _MOCK_SCORE_BREAKDOWN
    # Shared mock keys for BOTH tiers — engine-correct shapes,
    # so the same template bindings work in production.
    if not payload.get("scenarios"):
        payload["scenarios"] = _MOCK_SCENARIOS
    if not payload.get("period_returns_table"):
        payload["period_returns_table"] = _MOCK_PERIOD_RETURNS
    if not payload.get("risk_waterfall") and tier == "base":
        payload["risk_waterfall"] = _MOCK_RISK_WATERFALL
    if not payload.get("ai_stock_picks"):
        payload["ai_stock_picks"] = _MOCK_AI_STOCK_PICKS
    if not payload.get("kpi_sparklines"):
        payload["kpi_sparklines"] = _build_mock_sparklines()
    return payload


def _build_mock_sparklines() -> dict:
    """
    Generate 3 mock 12-point sparkline SVGs for the cover KPI strip.

    Uses tg_bot._sparkline_svg if available (production rendering path);
    falls back to a synthetic SVG matching the production output format
    when tg_bot can't import (e.g. local-dev without dotenv).
    """
    # Synthetic 12-month series — realistic banker shapes:
    #   CVaR worsens then recovers (V-shape)
    #   Sharpe steady improvement
    #   MaxDD drawdown then partial recovery
    cvar_pts   = [-0.030, -0.035, -0.041, -0.048, -0.055, -0.060,
                   -0.058, -0.052, -0.047, -0.045, -0.050, -0.052]
    sharpe_pts = [ 0.94,   1.02,   1.10,   1.05,   0.92,   0.88,
                    0.99,   1.12,   1.20,   1.28,   1.30,   1.34]
    mdd_pts    = [-0.040, -0.055, -0.072, -0.095, -0.110, -0.128,
                   -0.115, -0.108, -0.105, -0.100, -0.110, -0.128]
    try:
        from tg_bot import _sparkline_svg
        return {
            "cvar_svg":   _sparkline_svg(cvar_pts,   color="#3F8F5F", invert=True),
            "sharpe_svg": _sparkline_svg(sharpe_pts, color="#2F6FB3", invert=False),
            "mdd_svg":    _sparkline_svg(mdd_pts,    color="#C0492F", invert=True),
        }
    except Exception:
        # Inline minimal SVG fallback so the smoke render still shows
        # the sparkline cells with the gradient + polyline.
        def _fallback(values, color):
            vmin, vmax = min(values), max(values)
            rng = vmax - vmin or 1
            xs = [4 + i * 232 / 11 for i in range(12)]
            ys = [4 + 28 - (v - vmin) / rng * 28 for v in values]
            pts = " ".join(f"{x:.1f},{y:.1f}" for x, y in zip(xs, ys))
            return (f'<svg viewBox="0 0 240 36" preserveAspectRatio="none" '
                     f'xmlns="http://www.w3.org/2000/svg">'
                     f'<polyline points="{pts}" fill="none" stroke="{color}" '
                     f'stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"/>'
                     f'<circle cx="{xs[-1]:.1f}" cy="{ys[-1]:.1f}" r="3" '
                     f'fill="#FBFAF7" stroke="{color}" stroke-width="1.1"/>'
                     f'</svg>')
        return {
            "cvar_svg":   _fallback(cvar_pts,   "#3F8F5F"),
            "sharpe_svg": _fallback(sharpe_pts, "#2F6FB3"),
            "mdd_svg":    _fallback(mdd_pts,    "#C0492F"),
        }


# ── Mock fixtures (smoke render only — production uses real engine output) ──
# All shapes mirror what build_payload / engine helpers emit, so the same
# Jinja bindings work without modification in production.

_MOCK_STRESS_SCENARIOS = [
    {"name": "Equity DM −20%",  "port_pct": -0.158, "port_dollar":  -7900,
     "max_dd_pct": -0.220, "recovery_months": 6, "tag": "Tech sell-off"},
    {"name": "Equity EM −25%",  "port_pct": -0.075, "port_dollar":  -3750,
     "max_dd_pct": -0.110, "recovery_months": 4, "tag": "EM rout"},
    {"name": "Rates +100 bp",   "port_pct": -0.038, "port_dollar":  -1900,
     "max_dd_pct": -0.062, "recovery_months": 3, "tag": "Duration shock"},
    {"name": "HY Credit +200bp","port_pct": -0.028, "port_dollar":  -1400,
     "max_dd_pct": -0.044, "recovery_months": 3, "tag": "Credit widening"},
    {"name": "USD +10% (proxy)","port_pct":  0.012, "port_dollar":    600,
     "max_dd_pct": -0.018, "recovery_months": 2, "tag": "DXY rally"},
    {"name": "Oil −30%",        "port_pct": -0.014, "port_dollar":   -700,
     "max_dd_pct": -0.025, "recovery_months": 2, "tag": "Energy drawdown"},
    {"name": "CPI +1pp (proxy)","port_pct": -0.022, "port_dollar":  -1100,
     "max_dd_pct": -0.038, "recovery_months": 3, "tag": "Inflation surprise"},
]

_MOCK_EXPECTED_EFFECT = {
    "risk_index":      {"before": 62,    "after": 54,    "delta_pp": -8,    "favourable": True},
    "cvar_95":         {"before": -0.052,"after": -0.041,"delta_pp": 1.1,   "favourable": True},
    "sharpe":          {"before": 1.18,  "after": 1.32,  "delta_pp": 0.14,  "favourable": True},
    "max_drawdown":    {"before": -0.128,"after": -0.104,"delta_pp": 2.4,   "favourable": True},
    "vol":             {"before": 0.148, "after": 0.126, "delta_pp": -2.2,  "favourable": True},
    "max_erc_pct":     {"before": 0.244, "after": 0.168, "delta_pp": -7.6,  "favourable": True},
    "expected_return": {"before": 0.142, "after": 0.126, "delta_pp": -1.6,  "favourable": False},
    "it_share":        {"before": 0.62,  "after": 0.50,  "delta_pp": -12.0, "favourable": True},
}

_MOCK_MACRO_DRIVERS = {
    "as_of":  "2026-05-14",
    "regime": "Expansion (late)",
    "series": [
        {"id":"T10Y2Y","name":"Yield curve 10Y−2Y","value":"+0.18 pp","as_of":"2026-05-14","status":"ok",
         "comment":"положительный наклон — рецессия не сигналит"},
        {"id":"BAMLH0A0HYM2","name":"HY OAS (ICE BofA)","value":"312 bp","as_of":"2026-05-14","status":"ok",
         "comment":"спреды узкие — рынок не закладывает кредитный риск"},
        {"id":"NAPM","name":"ISM Manufacturing PMI","value":"51.4","as_of":"2026-04-01","status":"ok",
         "comment":"чуть выше 50 — производство расширяется"},
        {"id":"VIXCLS","name":"CBOE VIX","value":"14.2","as_of":"2026-05-14","status":"ok",
         "comment":"низкая ожидаемая волатильность — комфортная зона"},
        {"id":"T10YIE","name":"10Y Breakeven Inflation","value":"2.34%","as_of":"2026-05-14","status":"ok",
         "comment":"инфляционные ожидания у цели ФРС 2%"},
    ],
}

_MOCK_REGIME = {
    "label":      "Expansion (late)",
    "confidence": 72,
    "growth":     0.08,
    "cycle":      0.04,
    "explainers": [
        "SPY обгоняет IEF на +4.1% за 60 дней (рост vs облигации)",
        "Discretionary > Staples: +2.8% за 60д (цикличные on)",
        "EEM 60д +1.2% (EM risk-on)",
    ],
}

_MOCK_ACTION_PLAN = [
    {"ticker":"AAPL","action":"Sell 25%","reason":"HOTSPOT 24% риска; фиксируем часть прибыли (+25%)",
     "price":"$197.40","buy_zone":"$182–188","sell_target":"$215","stop_loss":"$175"},
    {"ticker":"KSPI","action":"Reduce 50%","reason":"TRC 22% при просадке −16.7% — концентрация выше порога",
     "price":"₸123.50","buy_zone":"₸115–119","sell_target":"₸140","stop_loss":"₸108"},
    {"ticker":"BND","action":"Hold","reason":"Hedge против rate shock; держим вес 20%",
     "price":"$72.18","buy_zone":"$71–73","sell_target":"$76","stop_loss":"$69"},
]

_MOCK_HOTSPOTS = [
    {"ticker":"AAPL","trc_pct":18.4,"reason":"TRC 18.4% при весе 50% — высокая концентрация"},
    {"ticker":"KSPI","trc_pct":22.1,"reason":"TRC 22% — KSPI EM hotspot"},
]

# Risk waterfall — engine shape from pdf_payload._build_risk_waterfall.
# Sample numbers chosen so sum_standalone − total = positive diversification.
_MOCK_RISK_WATERFALL = {
    "contributions": [
        {"ticker": "AAPL", "weight_pct": 50.0, "standalone_vol_pct": 24.5,
         "standalone_pp": 12.25, "standalone_share_pct": 67.3},
        {"ticker": "KSPI", "weight_pct": 30.0, "standalone_vol_pct": 18.0,
         "standalone_pp":  5.40, "standalone_share_pct": 29.7},
        {"ticker": "BND",  "weight_pct": 20.0, "standalone_vol_pct":  2.7,
         "standalone_pp":  0.54, "standalone_share_pct":  3.0},
    ],
    "sum_standalone_pp":     18.19,
    "total_vol_pp":          14.20,
    "diversification_pp":     3.99,
    "diversification_ratio":  0.219,
    "method": ("σᵢ = √Σᵢᵢ (annualised) · standalone = wᵢ·σᵢ · "
                "diversified = √(w'Σw) · benefit = Σstandalone − diversified"),
}

# 4-pillar scoring — engine shape from pdf_payload (asset_scores).
_MOCK_SCORE_BREAKDOWN = [
    {"ticker":"AAPL","fundamentals":"+2.0","valuations": "0.0","technicals":"+1.0","credit":"+1.0",
     "total":"+4.0","action":"Buy","action_color":"pos"},
    {"ticker":"KSPI","fundamentals":"+1.0","valuations":"+0.5","technicals":"-1.0","credit": "0.0",
     "total":"+0.5","action":"Hold","action_color":"neut"},
    {"ticker":"BND", "fundamentals": "0.0","valuations": "0.0","technicals": "0.0","credit":"+1.0",
     "total":"+1.0","action":"Hold","action_color":"neut"},
]

# Scenarios (benchmark comparison) — payload shape from pdf_payload (scenarios).
_MOCK_SCENARIOS = [
    {"name": "S&P 500", "excess": "+5.1%", "te": "8.4%", "ir": "0.61",
     "beating": True,  "color": "pos", "pnl": "+9.1%"},
]

# Multi-period returns — payload shape from results.period_returns_table.
# Engine builds this from benchmark_comparison.periods list.  Per-period
# shape: {period_label, portfolio_return, benchmark_return, excess}.
_MOCK_PERIOD_RETURNS = {
    "S&P 500": {
        "periods": [
            {"label":"1М",  "portfolio":"+2.0%", "benchmark":"+1.4%", "excess":"+0.6 пп"},
            {"label":"3М",  "portfolio":"+5.5%", "benchmark":"+3.6%", "excess":"+1.9 пп"},
            {"label":"6М",  "portfolio":"+9.4%", "benchmark":"+6.0%", "excess":"+3.4 пп"},
            {"label":"YTD", "portfolio":"+7.1%", "benchmark":"+4.4%", "excess":"+2.7 пп"},
            {"label":"12М", "portfolio":"+14.2%","benchmark":"+9.1%", "excess":"+5.1 пп"},
        ],
        "window_start": "2025-05-15",
        "window_end":   "2026-05-14",
    },
}

# AI stock picks — Haiku/Sonnet output shape.  DEEP-specific schema:
#   • 4 ideas across 4 buckets (risk_reduction · diversification · growth · hedge)
#   • 4-stage pipeline (FACTOR → REGIME → STRESS → RAG) — adds STRESS vs BASE's 3-stage
#   • candidates carry mini-info (beta, sector) — DEEP enrichment
#   • expected_effect lists 3 metrics — DEEP enrichment (BASE shows 2)
#   • sources include a stress reference chip — DEEP enrichment
# Engine populates via AdvisorBot.generate_stock_picks(tier='deep').
_MOCK_AI_STOCK_PICKS = {
    "risk_reduction": [
        {"idea_num":"01", "category":"Снижение риска", "priority":"high",
         "title":"Сократить долю AAPL с 50% до ~30%",
         "rationale":"AAPL помечен HOTSPOT — 18% всего риска портфеля при доходности "
                     "+25% (есть что фиксировать без убытка).  В late-cycle режиме при "
                     "коррекции IT перевес 50% становится критичным.",
         "candidates":[
            {"ticker":"TXN",  "name":"Texas Instruments", "scenario":"стабильный чип-производитель, vol/2 vs AAPL",
             "beta":0.85, "sector":"Technology"},
            {"ticker":"CSCO", "name":"Cisco",             "scenario":"зрелый тех с дивидендом и низкой бетой",
             "beta":0.72, "sector":"Technology"},
            {"ticker":"ACN",  "name":"Accenture",         "scenario":"IT-консалтинг с устойчивой выручкой",
             "beta":1.05, "sector":"Technology"},
         ],
         "pipeline":[
            ("FACTOR", "AAPL даёт 18% риска, HOTSPOT (TRC > 20% порога)"),
            ("REGIME", "late-cycle Expansion, рост vol ожидается в IT"),
            ("STRESS", "под Equity DM −20%: −15.8% vs −9.5% после rebalance"),
            ("RAG",    "Morgan Stanley: фиксировать прибыль в перегретых техах"),
         ],
         "expected_effect":[
            ("Вклад AAPL в риск", "18.4%", "~12%"),
            ("Доля IT-сектора",   "50%",   "~38%"),
            ("Sharpe Ratio",      "1.18",  "1.24"),
         ],
         "sources":["Quant Engine", "SEC EDGAR", "Stress: Equity DM −20%", "RAG: MS_TechOutlook_2026"],
        },
    ],
    "diversification": [
        {"idea_num":"02", "category":"Диверсификация", "priority":"medium",
         "title":"Добавить healthcare 10–15%",
         "rationale":"Текущая структура: 50% IT + 30% KSPI EM = 80% в двух высоко-β "
                     "секторах.  Healthcare исторически некоррелирован с IT, "
                     "стабилизирует портфель в late-cycle transitions.",
         "candidates":[
            {"ticker":"JNJ", "name":"Johnson & Johnson",  "scenario":"healthcare hedge, β 0.74",
             "beta":0.74, "sector":"Healthcare"},
            {"ticker":"UNH", "name":"UnitedHealth",       "scenario":"managed care, defensive growth",
             "beta":0.68, "sector":"Healthcare"},
            {"ticker":"PFE", "name":"Pfizer",             "scenario":"large-cap pharma с дивидендом",
             "beta":0.65, "sector":"Healthcare"},
         ],
         "pipeline":[
            ("FACTOR", "Concentration HHI = 3520 → 'concentrated' band"),
            ("REGIME", "late-cycle: защитные сектора начинают opt"),
            ("STRESS", "под Equity DM −20%: текущ. −15.8%, с healthcare −11.2%"),
            ("RAG",    "JPMorgan: 'islands of stability' в healthcare/staples"),
         ],
         "expected_effect":[
            ("Concentration HHI",     "3520",  "~2300"),
            ("Beta к рынку",          "1.18",  "~0.98"),
            ("Max Drawdown (модель)", "−12.8%","~−10.2%"),
         ],
         "sources":["Quant Engine", "Stress: Equity DM −20%", "RAG: JPM_Strategy_Q2_2026"],
        },
    ],
    "growth": [
        {"idea_num":"03", "category":"Рост качества", "priority":"medium",
         "title":"Усилить позицию в MSFT при откатах",
         "rationale":"MSFT даёт качественный экспозиш в IT без HOTSPOT: вес 8%, "
                     "TRC только 9%.  4-Pillar Total +3.5 (sky-high). "
                     "Buy zone $402-408 (SMA50 − 1·ATR).",
         "candidates":[
            {"ticker":"MSFT", "name":"Microsoft",        "scenario":"core add — quality at scale",
             "beta":0.98, "sector":"Technology"},
            {"ticker":"GOOGL","name":"Alphabet",         "scenario":"diversified ad+cloud экспозиш",
             "beta":1.05, "sector":"Communication Services"},
            {"ticker":"V",    "name":"Visa",             "scenario":"payments — высокий ROE, низкий β",
             "beta":0.92, "sector":"Financial Services"},
         ],
         "pipeline":[
            ("FACTOR", "MSFT score F+1 V+1 T+1 C+0.5 (Total +3.5)"),
            ("REGIME", "late-cycle: high-quality holds value лучше"),
            ("STRESS", "под все 7 сценариев: −7% медиана (лучше портфеля)"),
            ("RAG",    "Goldman: maintain quality bias in tech"),
         ],
         "expected_effect":[
            ("MSFT weight",           "8%",   "12%"),
            ("Quality score (port)",  "+1.8", "+2.4"),
            ("Sharpe Ratio",          "1.18", "1.21"),
         ],
         "sources":["Quant Engine", "SEC EDGAR", "Stress: 7-scenario median", "RAG: GS_Q2_2026"],
        },
    ],
    "hedge": [
        {"idea_num":"04", "category":"Хедж rate-shock", "priority":"low",
         "title":"Купить TLT/IEF на 5% при росте 10Y > 5%",
         "rationale":"Портфель β-Rates = −0.30 (умеренная rate-sensitivity).  При "
                     "hawkish surprise Fed +50bp портфель просядет на −4.2%.  TLT "
                     "(20Y bonds) на 5% сглаживает duration shock.",
         "candidates":[
            {"ticker":"TLT", "name":"iShares 20Y T-Bond ETF", "scenario":"duration hedge, β-Rates +0.85",
             "beta":-0.35, "sector":"Fixed Income"},
            {"ticker":"IEF", "name":"iShares 7-10Y T-Bond",   "scenario":"мягче duration vs TLT",
             "beta":-0.20, "sector":"Fixed Income"},
            {"ticker":"AGG", "name":"iShares Core US Bond",   "scenario":"broad-market bond exposure",
             "beta":-0.15, "sector":"Fixed Income"},
         ],
         "pipeline":[
            ("FACTOR", "β-Rates портфеля = −0.30 (rate-sensitive)"),
            ("REGIME", "late-cycle: Fed surprises возможны"),
            ("STRESS", "под Rates +100bp: −3.8% портфеля, с TLT 5% → −2.6%"),
            ("RAG",    "Bank consensus: 10Y range 4.2-5.0% Q3 2026"),
         ],
         "expected_effect":[
            ("β-Rates",          "−0.30", "−0.18"),
            ("Stress Rates+100bp","−3.8%", "−2.6%"),
            ("Vol (год.)",        "14.8%", "13.9%"),
         ],
         "sources":["Quant Engine", "FRED: T10Y2Y", "Stress: Rates +100bp", "RAG: Bank consensus"],
        },
    ],
}


MOCK_DATA: dict = {}   # lazily filled by the CLI / smoke entry-point below.


DEEP_VERSION  = os.getenv("REPORT_DEEP_VERSION",  "v3").lower()
BASIC_VERSION = os.getenv("REPORT_BASIC_VERSION", "v3").lower()


def _select_template(tier: str) -> str:
    """
    Pick the template name based on tier and feature flag.

    Feature flag layering:
      REPORT_VERSION       v1 → legacy dark theme (single file)
                            v2 → light theme hybrid (snapshot-bar + q-blocks)
      REPORT_DEEP_VERSION  v3 → prototype-grade banker design (DEFAULT)
                                  cream theme, 5 pages, 8-axis radar,
                                  banker-grade KPI cards, full data-driven
                                  stress / effect / macro / regime panels
                            v2 → legacy hybrid (fallback)
      REPORT_BASIC_VERSION v3 → prototype-grade banker design (DEFAULT)
                                  cream theme, 4 pages
                            v2 → legacy hybrid (fallback)

    Both v3 templates render against the same payload schema as v2 — no
    payload changes needed for the switch.  Set REPORT_*_VERSION=v2 in
    env to roll back without redeploying code.
    """
    if REPORT_VERSION == "v1":
        return "report.html"
    if (tier or "base").lower() == "deep":
        if DEEP_VERSION == "v3":
            return "report_deep_v3.html"
        return "report_deep.html"
    # BASE tier
    if BASIC_VERSION == "v3":
        return "report_basic_v3.html"
    return "report_basic.html"


def _jinja_env() -> Environment:
    return Environment(
        loader     = FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape = select_autoescape(["html"]),
    )


def render_report_html(data_dict: dict | None,
                        user_id:   int | str,
                        report_type: str = "Базовый отчёт",
                        tier:        str = "base",
                        generated_at: str | None = None) -> str:
    """
    Render the Jinja template to an HTML string.

    Args:
        data_dict   : Payload from pdf_payload.build_payload.  When None,
                       a synthetic mock payload is built (smoke-test only).
        user_id     : Telegram user ID (shown in the report header).
        report_type : Human-readable label for the header badge.
        tier        : 'base' | 'deep' — selects the template.
        generated_at: Optional override for the report timestamp; defaults
                       to "now" in UTC+5.

    Returns:
        The rendered HTML as a string.  Does NOT write to disk — pass to
        write_report_html() or services.report_storage.upload_report().
    """
    payload  = data_dict if data_dict is not None else _mock_payload(tier)
    template = _jinja_env().get_template(_select_template(tier))
    return template.render(
        data         = payload,
        user_id      = user_id,
        report_type  = report_type,
        generated_at = generated_at or datetime.now().strftime("%d.%m.%Y %H:%M UTC+5"),
    )


def write_report_html(html: str, user_id: int | str, tier: str,
                       output_dir: Path | None = None) -> Path:
    """
    Persist a rendered HTML string to a local file.

    Path: <output_dir>/<user_id>_<YYYY-MM-DD>_<tier>.html  (default dir
    is OUTPUT_DIR = /tmp/user_reports).  Caller is responsible for
    uploading the file to GCS or sending the path to the user.

    Returns the absolute Path that was written.
    """
    out_dir = Path(output_dir or OUTPUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")
    path  = out_dir / f"{user_id}_{today}_{tier}.html"
    path.write_text(html, encoding="utf-8")
    logger.info("HTML report written: %s (%.1f KB)", path, path.stat().st_size / 1024)
    return path


def generate_portfolio_html(data_dict: dict | None,
                              user_id:   int | str,
                              report_type: str = "Базовый отчёт",
                              tier:        str = "base") -> str:
    """
    Convenience wrapper: render + write to disk, returns the file path.

    Mirrors the old generate_portfolio_pdf() signature so callers in
    tg_bot.py only need to swap the function name.
    """
    html = render_report_html(data_dict, user_id, report_type, tier)
    return str(write_report_html(html, user_id, tier))


# ── CLI smoke-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    for t in ("base", "deep"):
        p = generate_portfolio_html(
            None, user_id="smoke", tier=t,
            report_type="Базовый отчёт" if t == "base" else "Глубокий сценарный анализ",
        )
        print(f"[{t}] → {p}")


__all__ = [
    "render_report_html",
    "write_report_html",
    "generate_portfolio_html",
    "MOCK_DATA",
    "TEMPLATE_DIR",
    "OUTPUT_DIR",
    "REPORT_VERSION",
]
